surface.CreateFont("deadremains.hud.big", {font = "AvenirNext LT Pro Regular", size = 60, weight = 400})
surface.CreateFont("deadremains.menu.label", {font = "Bebas Neue", size = 64, weight = 400})
surface.CreateFont("deadremains.menu.title", {font = "Bebas Neue", size = 40, weight = 400})
surface.CreateFont("deadremains.menu.skill_category", {font = "Bebas Neue", size = 32, weight = 300})
surface.CreateFont("deadremains.menu.infoNumber", {font = "Bebas Neue", size = 48, weight = 300})
surface.CreateFont("deadremains.menu.infoText", {font = "Bebas Neue", size = 28, weight = 300})
surface.CreateFont("deadremains.menu.gridTitle", {font = "Bebas Neue", size = 26, weight = 200})
surface.CreateFont("deadremains.menu.inventoryTitle", {font = "Bebas Neue", size = 32, weight = 200})
surface.CreateFont("deadremains.notification.title", {font = "AvenirNext LT Pro Regular", size = 22, weight = 400})
surface.CreateFont("deadremains.notification.action", {font = "Bebas Neue", size = 38, weight = 400})
--surface.CreateFont("deadremains.hud.big.blur", {font = "AvenirNext LT Pro Regular", size = 60, weight = 400, blursize = 6, antialias = false})