surface.CreateFont("deadremains.hud.big", {font = "AvenirNext LT Pro Regular", size = 60, weight = 400})
surface.CreateFont("deadremains.menu.title", {font = "Bebas Neue", size = 40, weight = 400})
surface.CreateFont("deadremains.menu.skill_category", {font = "Bebas Neue", size = 32, weight = 300})
surface.CreateFont("deadremains.notification.title", {font = "AvenirNext LT Pro Regular", size = 22, weight = 400})
surface.CreateFont("deadremains.notification.action", {font = "Bebas Neue", size = 38, weight = 400})
--surface.CreateFont("deadremains.hud.big.blur", {font = "AvenirNext LT Pro Regular", size = 60, weight = 400, blursize = 6, antialias = false})